name: Java CI with Maven - Test and packages
on:
  pull_request:
    branches:
      - main
jobs:
    Check:
      name: Check
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Action
          uses: actions/setup-java@v4
          with:
            distribution: 'corretto'
            java-version: '21'
        - name: Build and Test with Maven
          run: mvn -B package